### ISSUE TITLE
there is no randomness

### ISSUE THREAD

**Issue by StoneCypher** [forestbelton/egg#1]
nor is there anything from which i could make randomness, such as time, or a js ffi

**Comment by forestbelton** [comment]
Thanks, I added the `mR` operator and expanded the `%` operator for this purpose.

**Comment by StoneCypher** [comment]
two letter operators in a golf language 😅

LEARN YOU SOME UNICODE BOY

**Comment by forestbelton** [comment]
I think you'll be surprised at the information density that I can reach even with just ASCII - got some really cool operators planned.

**Comment by StoneCypher** [comment]
![image](https://user-images.githubusercontent.com/77482/30395170-24aa894c-987a-11e7-9151-96f586a4b094.png)
