### ISSUE TITLE
cannot find working syntax for <

### ISSUE THREAD

**Issue by StoneCypher** [forestbelton/egg#2]
tried

```egg
1,N"A""B""C"<
1 N"A""B""C"<

1<N"A""B""C"

<1,N"A""B""C"
<1 N"A""B""C"
```

**Comment by forestbelton** [comment]
`<` currently supports three clauses:

* `array`, `float`
* `bigint`, `bigint`
* `float`, `float`

The bottom 3 expressions will not work as there is not enough data on the stack (RPN). The top two would work if there was a matching clause for the arguments (`string`, `string`) implemented by the `<` operator.

Examples of working expressions:

```
1 2 <
==> 1

4.3 2. <
==> 0
```

String comparison is reasonable and should be added. I will extend the `<`, `>`, and `=` operators for this.

**Comment by StoneCypher** [comment]
oh so that's not the thing i thought i was getting

i'm looking for a mechanism to get a cell out of an array.  i thought i had to build it out of `drop/2` and `take/2`

htf do you index an array

**Comment by forestbelton** [comment]
No mechanism to do that currently either 😸

**Comment by StoneCypher** [comment]
```
<     arrayfloat     Drops the first N elements from an array.
```

... well, you _did_ say you were getting into statistics
![image](https://user-images.githubusercontent.com/77482/30408090-644d2c1c-98b1-11e7-9841-77f59c14c74f.png)

**Comment by forestbelton** [comment]
Okay, you should be able to access arrays using the `^` operator now.

**Comment by StoneCypher** [comment]
"i implemented it 90 degrees clockwise of what the manual says"

works for me 😀
