### ISSUE TITLE
cannot find working syntax for ^

### ISSUE THREAD

**Issue by StoneCypher** [forestbelton/egg#5]
tried

```
1,N"A""B""C"^
1 N"A""B""C"^

1^N"A""B""C"

^1,N"A""B""C"
^1 N"A""B""C"
```

note: methods 1,2,5 cannot find clause; methods 2,3 unsupported operator.

maybe is the interpreter just out of date?

**Comment by forestbelton** [comment]
`"A" "B" "C"] 1 ^` should work for this purpose. Feel free to re-open if that's not the case.
